server:
  port: 80
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: mappings,beans,sessions

logging:
  level:
    sql: debug
    web: debug
spring:
  application:
    name: resolute
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RESOLUTE_USER}
    password: ${RESOLUTE_PASS}
    url: ${RESOLUTE_LINK}