whatsapp:
  key: ${WH_KEY}
email:
  id : jmswiftapp@gmail.com
  password : ${RESOLUTE_EMAIL_PASS}

server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: keystore.jks
    key-store-password: changeit
  port: 443
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: mappings,beans,sessions

logging:
  level:
    sql: debug
    web: debug
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jmswiftapp@gmail.com
    password: ${RESOLUTE_EMAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: resolute
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      format_sql: true
      show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RESOLUTE_USER}
    password: ${RESOLUTE_PASS}
    url: ${RESOLUTE_LINK}