logging:
  level:
    sql: debug
    web: debug
spring:
  application:
    name: resolute
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      format_sql: true
      show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    username: sql6701811
#    password: pmqc2T6PGf
#    url: jdbc:mysql://sql6.freesqldatabase.com:3306/sql6701811
    username: root
    password: hello
    url: jdbc:mysql://localhost:3306/resolve?createDatabaseIfNotExist=true