package com.resolute.zero.templates;

public enum Arguments {
    BORROWER,LOAN_RECALL_NOTICE,OUTSTANDING_AMOUNT,BANK,LRN_LINK,
    INTENT_LETTER,INTENT_LETTER_LINK,
    REFERENCE_LETTER,REFERENCE_LETTER_LINK,
    CONSENT_LETTER,DATE,CONSENT_LETTER_LINK,
    CASE_NUMBER,HEARING_SEQUENCE,ATTENDANCE,SOC_AND_SEC17_APPLICATION,
    MEETING_LINK,
    LINK_FOR_REWARD
}
